---
driver:
  name: vagrant
  driver_config:
    require_chef_omnibus: latest

provisioner:
  name: chef_zero
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
- name: debian-6.0.10-amd64
  driver_plugin: vagrant
  driver_config:
    box: ffuenf/debian-6.0.10-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/debian-6.0.10-amd64
    box_check_update: true

- name: debian-7.9.0-amd64
  driver_plugin: vagrant
  driver_config:
    box: ffuenf/debian-7.9.0-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/debian-7.9.0-amd64
    box_check_update: true

- name: debian-8.2.0-amd64
  driver_plugin: vagrant
  driver_config:
    box: ffuenf/debian-8.2.0-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/debian-8.2.0-amd64
    box_check_update: true

- name: ubuntu-14.04.3-server-amd64
  driver_plugin: vagrant
  driver_config:
    box: ffuenf/ubuntu-14.04.3-server-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/ubuntu-14.04.3-server-amd64
    box_check_update: true

- name: ubuntu-15.04-server-amd64
  driver_plugin: vagrant
  driver_config:
    box: ffuenf/ubuntu-15.04-server-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/ubuntu-15.04-server-amd64
    box_check_update: true

suites:
- name: default
  run_list:
    - recipe[dop_nginx::default]
    - recipe[dop_nginx::geoip]
    - recipe[dop_nginx::naxsi]
    - recipe[dop_nginx::ngx_pagespeed]
